---
- name: Crear estructura de directorios
  file:
    path: "/tmp/2do_parcial/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - alumno
    - equipo

- name: Crear datos_alumno.txt usando template
  template:
    src: datos_alumno.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt
    mode: '0644'

- name: Crear datos_equipo.txt usando template
  template:
    src: datos_equipo.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt
    mode: '0644'

- name: Configurar sudoers para 2PSupervisores
  become: yes
  lineinfile:
    path: /etc/sudoers.d/2PSupervisores
    line: '%2PSupervisores ALL=(ALL) NOPASSWD: ALL'
    create: yes
    mode: '0440'
    validate: 'visudo -cf %s'
